#! /bin/bash

rm errors_fs1
rm errors_fs3
rm areas

for n in 8 10 12 14 16 18 20 22 24 26 28 30 32 ; do

    echo ------- n= $n ------------

    echo fs_method=1
    python3 stone.py $n 2 1 > opla
    grep errv opla >> errors_fs1
    grep area opla | grep meas >> areas

    echo fs_method=3
    python3 stone.py $n 2 3 > opla
    grep errv opla >> errors_fs3

done
 
