#! /bin/bash

rm errors_*
rm vrms_*
rm *.ascii

for nq in 2; do

    for rs in 6 8 10 12 14 16 18 20 22 24 26 28 30 32 36 40 44 48 56 64 72 80 88 96; do 

        echo $rs 

        python3 stone.py $rs $rs 0 0 0 0 $nq 0.25 > opla

        grep errv opla >> errors_nq${nq}_even
        grep vrms opla >> vrms_nq${nq}_even

    done

done

rm opla
