#! /bin/bash

rm vy*.ascii

eta1=21

for rs in 16 32 48 64 80 96; do

    for eta2 in 17 17.5 18 18.5 19 19.5 20 20.5 20.7 21 21.2 21.5 22 22.5 23 23.5 24 25; do

        echo $rs $eta1 $eta2

        python3 stone.py $rs $rs 0 0 $eta1 $eta2 2 0.25 > opla

        grep RT opla >> vy_${rs}.ascii

    done

done

rm opla
