#! /bin/bash

rm errors_*
rm vrms_*
rm *.ascii

#for nq in 2 3 4 5 6; do
for nq in 2; do

    #for rs in 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 32 37 42 48 53 ; do
    #for rs in {6..81} ; do
    for rs in 8 16 20 32 40 48 56 64 72 80 88 96 104 112 120 128  ; do

        echo $rs 

        python3 stone.py $rs $rs 0 0 0 0 $nq 0.25 > opla

        grep errv opla >> errors_nq$nq
        grep vrms opla >> vrms_nq$nq

    done

done

rm opla
