#! /bin/bash

for n in 33; do
    for Ra in 700 800 801 802 803 804 805 806 807 808 809 810 900; do 

        echo n= $n -Ra= $Ra
        python3 stone.py $n $Ra  > opla
        grep ssss opla >> ssss_n${n}

    done
done

for n in 49 65; do
    for Ra in 700 790 791 792 793 794 795 796 797 798 799 800 900; do 

        echo n= $n -Ra= $Ra
        python3 stone.py $n $Ra  > opla
        grep ssss opla >> ssss_n${n}

    done
done


for n in 97; do
    for Ra in 700 780 781 782 783 784 785 786 787 788 789 790 800 900; do 

        echo n= $n -Ra= $Ra
        python3 stone.py $n $Ra  > opla
        grep ssss opla >> ssss_n${n}

    done
done






mv ssss_* results_onset
