#! /bin/bash

rm *.ascii 

for n in {8..80} ; do
    for s in {1..4} ; do 
        echo nelx=nely= $n
        python3 stone.py  $n $n 0 > opla
        grep errv opla >> errors.ascii
        grep assembly opla >> assembly.ascii
        grep Build opla >> build.ascii
        grep Solve opla >> solve.ascii
        grep csr opla >> convert2csr.ascii
        grep split opla >> split.ascii
        grep press opla >> press.ascii
        grep bc opla >> bc.ascii
    done
done

for n in 96 104 112 120 128 144 ; do
    for s in {1..4} ; do 
        echo nelx=nely= $n
        python3 stone.py  $n $n 0 > opla
        grep errv opla >> errors.ascii
        grep assembly opla >> assembly.ascii
        grep Build opla >> build.ascii
        grep Solve opla >> solve.ascii
        grep csr opla >> convert2csr.ascii
        grep split opla >> split.ascii
        grep press opla >> press.ascii
        grep bc opla >> bc.ascii
    done
done



