#! /bin/bash

rm -f errors.ascii
rm -f build.ascii
rm -f solve.ascii

for n in {8..80} ; do
    for s in {1..10} ; do 
        echo nelx=nely= $n
        python3 stone.py  $n $n 0 > opla
        grep errv opla >> errors.ascii
        grep Build opla >> build.ascii
        grep Solve opla >> solve.ascii 
    done
done
