program subductionGeo

! makes the .geo file of a basic subduction situation,
! that can be meshed by Gmsh.
! The model contains:

! deep earth material (material 1)
! an overriding plate (material 2)
! a subducting  plate (material 3)

! The fault lays in the y direction on x=0
! z is negative downward into the earth; he surface at z=0

! The domain can be configure by the parameters described directly below.

! output is written to subduction.geo

! Made by Lukas van de Wiel, 25 Jan 2022



implicit none

!*******     configure me here    *************

! distance are in meters.

! along the fault. Domain goes -1/2 domainLength to +1/2 domainLength
double precision, parameter :: domainWidth = 100000d0  

! overriding and subductating plate have the same thickness.
double precision, parameter :: slabThickness = 30000d0

! vertical. Domain geoes from 0 at surface to -domainDepth
! The user is assumed clever enough to pick a domainDepth
! large enough so that the hanging slab fits inside.
double precision, parameter :: domainDepth = 100000d0

! orthogonal to the fault. Domain goes -1/2 domainWidth to +1/2 domainWidth
double precision, parameter :: domainLength = 300000d0 


double precision, parameter :: elementSize = 5000d0

! the bend of the subducting plate is split into this many straight sections
integer, parameter          :: nBendSteps = 10 ! max 999

! the slab sticks out this far past the bend
double precision, parameter :: hangingSlabLength = 50000d0

!*******   end of configuration parameter  *******


double precision, parameter :: pi = 4d0 * atan(1d0)

double precision            :: angle, maxAngle
integer                     :: ibend
double precision            :: xc, yc
 
double precision            :: innerRadius, outerRadius

double precision            :: si, so, ci, co ! (sine/cosine + inner/outer radius)
double precision            :: delta
integer                     :: iLine, iEdge

open(unit=42, file="subduction.geo")


write(42,*) "// Generated by subductionGeo."

write(42,*) "elemSize = ", elementSize,";"

write(42,*) "halfL = ", domainLength * 0.5,";"
write(42,*) "halfW = ", domainWidth * 0.5,";"
write(42,*) "slabThickness = ", slabThickness ,";"
write(42,*) "domainDepth = ", domainDepth  ,";"

! very outside of subducting slab
write(42,*) "Point(1) = {halfL,  halfW, -slabThickness, elemSize};"
write(42,*) "Point(2) = {halfL,  halfW, 0,              elemSize};"
write(42,*) "Point(3) = {halfL, -halfW, 0,              elemSize};"
write(42,*) "Point(4) = {halfL, -halfW, -slabThickness, elemSize};"

write(42,*) "Line(1) = {1,2};"
write(42,*) "Line(2) = {2,3};"
write(42,*) "Line(3) = {3,4};"
write(42,*) "Line(4) = {4,1};"

write(42,*) "Line Loop(1) = {1, 2, 3, 4};"
write(42,*) "Plane Surface(1) = {1};"
write(42,*) "Physical Surface(1) = {1};"


! right plane outside of overriding slab
write(42,*) "Point(21) = {-halfL,  halfW, -slabThickness, elemSize};"
write(42,*) "Point(22) = {-halfL,  halfW, 0,              elemSize};"
write(42,*) "Point(23) = {-halfL, -halfW, 0,              elemSize};"
write(42,*) "Point(24) = {-halfL, -halfW, -slabThickness, elemSize};"

write(42,*) "Line(21) = {21,22};"
write(42,*) "Line(22) = {22,23};"
write(42,*) "Line(23) = {23,24};"
write(42,*) "Line(24) = {24,21};"

write(42,*) "Line Loop(21) = {21, 22, 23, 24};"
write(42,*) "Plane Surface(2) = {21};"
write(42,*) "Physical Surface(2) = {21};"


! add the the bend

write(42,*) "// bend"

xc = 0d0
yc = - slabThickness / (1d0 - 0.5 * sqrt(2d0))

maxAngle = pi / 4d0

innerRadius = -yc
outerRadius = -yc - slabThickness 

do ibend = 1, nBendSteps
    angle = maxAngle * dble(ibend-1) / dble(nBendSteps-1)

    ci =  cos(angle) * innerRadius
    co =  cos(angle) * outerRadius
    si = -sin(angle) * innerRadius
    so = -sin(angle) * outerRadius

    ! add points of the next bend step
    write(42,*) "Point(",1000 + ibend,") = {",si,",  halfW,", yc+ci,", elemSize};"
    write(42,*) "Point(",2000 + ibend,") = {",so,",  halfW,", yc+co,", elemSize};"
    write(42,*) "Point(",3000 + ibend,") = {",so,", -halfW,", yc+co,", elemSize};"
    write(42,*) "Point(",4000 + ibend,") = {",si,", -halfW,", yc+ci,", elemSize};"

    ! construct the ring
    write(42,*) "Line(",1000 + ibend,") = {",1000 + ibend,",",2000 + ibend,"};"
    write(42,*) "Line(",2000 + ibend,") = {",2000 + ibend,",",3000 + ibend,"};"
    write(42,*) "Line(",3000 + ibend,") = {",3000 + ibend,",",4000 + ibend,"};"
    write(42,*) "Line(",4000 + ibend,") = {",4000 + ibend,",",1000 + ibend,"};"

    ! attach it to the previous ring
    if (iBend.gt.1) then
        write(42,*) "Line(",5000 + ibend,") = {",1000 + ibend,",",1000 + ibend - 1,"};"
        write(42,*) "Line(",6000 + ibend,") = {",2000 + ibend,",",2000 + ibend - 1,"};"
        write(42,*) "Line(",7000 + ibend,") = {",3000 + ibend,",",3000 + ibend - 1,"};"
        write(42,*) "Line(",8000 + ibend,") = {",4000 + ibend,",",4000 + ibend - 1,"};"

        ! construct the planes connecting this ring with the previous one

        ! outer curve
        write(42,*) "Line Loop(",1000 + ibend,") = {",  2000 + ibend - 1, &
                                                  ",", -7000 - ibend, &
                                                  ",", -2000 - ibend, &
                                                  ",",  6000 + ibend,"};"
        
        write(42,*) "Plane Surface(",1000 + ibend,") = {",1000 + ibend,"};"
        write(42,*) "Physical Surface(",1000 + ibend,") = {",1000 + ibend,"};"


        ! inner curve
        write(42,*) "Line Loop(",2000 + ibend,") = {", -4000 - ibend + 1, &
                                                  ",", -8000 - ibend, &
                                                  ",",  4000 + ibend, &
                                                  ",",  5000 + ibend,"};"

        write(42,*) "Plane Surface(",2000 + ibend,") = {",2000 + ibend,"};"
        write(42,*) "Physical Surface(",2000 + ibend,") = {",2000 + ibend,"};"


        ! side on positive y side
        write(42,*) "Line Loop(",3000 + ibend,") = {",  1000 + ibend - 1, &
                                                  ",", -6000 - ibend, &
                                                  ",", -1000 - ibend, &
                                                  ",",  5000 + ibend,"};"

        write(42,*) "Plane Surface(",3000 + ibend,") = {",3000 + ibend,"};"
        write(42,*) "Physical Surface(",3000 + ibend,") = {",3000 + ibend,"};"


        ! side on negative y side
        write(42,*) "Line Loop(",4000 + ibend,") = {",  3000 + ibend - 1, &
                                                  ",", -8000 - ibend, &
                                                  ",", -3000 - ibend, &
                                                  ",",  7000 + ibend,"};"

        write(42,*) "Plane Surface(",4000 + ibend,") = {",4000 + ibend,"};"
        write(42,*) "Physical Surface(",4000 + ibend,") = {",4000 + ibend,"};"
    endif

enddo


write(42,*) "// sides of flat surface area of horizontal slab"

! yip, I messed up...
write(42,*) "Line(11) = {2,1001};"
write(42,*) "Line(12) = {1,2001};"
write(42,*) "Line(13) = {4,3001};"
write(42,*) "Line(14) = {3,4001};"

write(42,*) "Line Loop(31) = {11, 1001, -12, 1 };"
write(42,*) "Plane Surface(31) = {31};"
write(42,*) "Physical Surface(31) = {31};"

write(42,*) "Line Loop(32) = {12, 2001, -13, 4 };"
write(42,*) "Plane Surface(32) = {32};"
write(42,*) "Physical Surface(32) = {32};"

write(42,*) "Line Loop(33) = {13, 3001, -14, 3 };"
write(42,*) "Plane Surface(33) = {33};"
write(42,*) "Physical Surface(33) = {33};"

write(42,*) "Line Loop(34) = {14, 4001, -11, 2 };"
write(42,*) "Plane Surface(34) = {34};"
write(42,*) "Physical Surface(34) = {34};"

write(42,*) "//  hanging slab"

delta = hangingSlabLength / sqrt(2d0)

write(42,*) "Point(41) = {",si-delta,",  halfW,", yc+ci-delta,", elemSize};"
write(42,*) "Point(42) = {",so-delta,",  halfW,", yc+co-delta,", elemSize};"
write(42,*) "Point(43) = {",so-delta,", -halfW,", yc+co-delta,", elemSize};"
write(42,*) "Point(44) = {",si-delta,", -halfW,", yc+ci-delta,", elemSize};"

write(42,*) "Line(41) = {41, ",1000 + nBendSteps,"};"
write(42,*) "Line(42) = {42, ",2000 + nBendSteps,"};"
write(42,*) "Line(43) = {43, ",3000 + nBendSteps,"};"
write(42,*) "Line(44) = {44, ",4000 + nBendSteps,"};"

write(42,*) "Line(51) = {41,42};"
write(42,*) "Line(52) = {42,43};"
write(42,*) "Line(53) = {43,44};"
write(42,*) "Line(54) = {44,41};"

write(42,*) "//  sides of flat surface area of overriding slab"

write(42,*) "Line(61) = {21, ",1000 + ibend -1,"};"
write(42,*) "Line(62) = {22, 1001};"
write(42,*) "Line(63) = {23, 4001};"
write(42,*) "Line(64) = {24, ",4000 + ibend -1,"};"


write(42,*) "// add the surrounding box"


! very outside of subducting slab
write(42,*) "Point(71) = {halfL,   halfW, -domainDepth, elemSize};"
write(42,*) "Point(72) = {halfL,  -halfW, -domainDepth, elemSize};"
write(42,*) "Point(73) = {-halfL, -halfW, -domainDepth, elemSize};"
write(42,*) "Point(74) = {-halfL,  halfW, -domainDepth, elemSize};"

write(42,*) "Line(71) = {71,72};"
write(42,*) "Line(72) = {72,73};"
write(42,*) "Line(73) = {73,74};"
write(42,*) "Line(74) = {74,71};"

write(42,*) "Line Loop(7) = {71, 72, 73, 74};"
write(42,*) "Plane Surface(7) = {7};"
write(42,*) "Physical Surface(7) = {7};"

! vertical supports around the deep earth
write(42,*) "Line(81) = {71,1};"
write(42,*) "Line(82) = {72,4};"
write(42,*) "Line(83) = {73,24};"
write(42,*) "Line(84) = {74,21};"

! deep earth at side of overriding plate
write(42,*) "Line Loop(12) = {73, 84, -24, -83};"
write(42,*) "Plane Surface(12) = {12};"
write(42,*) "Physical Surface(12) = {12};"

! deep earth at side of subducting plate
write(42,*) "Line Loop(11) = {71, 82, 4, -81};"
write(42,*) "Plane Surface(11) = {11};"
write(42,*) "Physical Surface(11) = {11};"

! surface of overriding plate
write(42,*) "Line Loop(22) = {62, -4001, -63, -22};"
write(42,*) "Plane Surface(22) = {22};"
write(42,*) "Physical Surface(22) = {22};"

! bottom of overriding plate
write(42,*) "Line Loop(23) = {61,", -4000-nBendSteps, " , -64, 24};"
write(42,*) "Plane Surface(23) = {23};"
write(42,*) "Physical Surface(23) = {23};"

! 5 simple sides of the hanging slab
! end of the slab
write(42,*) "Line Loop(51) = {51,52,53,54};"
write(42,*) "Plane Surface(51) = {51};"
write(42,*) "Physical Surface(51) = {51};"

write(42,*) "Line Loop(52) = {51,42,", -1000-nBendSteps, ",-41};"
write(42,*) "Plane Surface(52) = {52};"
write(42,*) "Physical Surface(52) = {52};"

write(42,*) "Line Loop(53) = {54,41,", -4000-nBendSteps, ",-44};"
write(42,*) "Plane Surface(53) = {53};"
write(42,*) "Physical Surface(53) = {53};"

write(42,*) "Line Loop(54) = {53,44,", -3000-nBendSteps, ",-43};"
write(42,*) "Plane Surface(54) = {54};"
write(42,*) "Physical Surface(54) = {54};"

write(42,*) "Line Loop(55) = {42,", 2000+nBendSteps, ",-43,-52};"
write(42,*) "Plane Surface(55) = {55};"
write(42,*) "Physical Surface(55) = {55};"



! the panels that have edges along the bend

! front of deep earth
write(42,*) "Line Loop(61) = {"
do iLine = 1, nBendSteps-1
    write(42,*) 7000+nBendSteps-iLine+1, ","
enddo
write(42,*) "-13, -82, 72, 83, 64, -44, -53, 43};"
write(42,*) "Plane Surface(61) = {61};"
write(42,*) "Physical Surface(61) = {61};"

! back of deep earth
write(42,*) "Line Loop(62) = {"
do iLine = 1, nBendSteps-1
    write(42,*) 6000+nBendSteps-iLine+1, ","
enddo
write(42,*) "-12, -81, -74, 84, 61, -41, 51, 42};"
write(42,*) "Plane Surface(62) = {62};"
write(42,*) "Physical Surface(62) = {62};"

! front of overriding slab
write(42,*) "Line Loop(63) = {"
do iLine = 1, nBendSteps-1
    write(42,*) 8000+nBendSteps-iLine+1, ","
enddo
write(42,*) "-63, 23, 64};"
write(42,*) "Plane Surface(63) = {63};"
write(42,*) "Physical Surface(63) = {63};"

! back of overriding slab
write(42,*) "Line Loop(64) = {"
do iLine = 1, nBendSteps-1
    write(42,*) 5000+nBendSteps-iLine+1, ","
enddo
write(42,*) "-62, -21, 61};"
write(42,*) "Plane Surface(64) = {64};"
write(42,*) "Physical Surface(64) = {64};"

! volumes. We are getting somewhere!


! 1, the deep earth

write(42,*) "Surface Loop(1) = {"
do iLine = 2, nBendSteps
    write(42,*) 1000+iLine, ","
enddo
write(42,*) "32, 11, 7, 12, 23, 53, 51, 55, 61, 62};"
write(42,*) "Volume(1) = {1};"
write(42,*) "Physical Volume(1) = {1};"

! 2 the overriding slab

write(42,*) "Surface Loop(2) = {"
do iLine = 2, nBendSteps
    write(42,*) 2000+nBendSteps, ","
enddo
write(42,*) "2, 22, 23, 63, 64};"
write(42,*) "Volume(2) = {2};"
write(42,*) "Physical Volume(2) = {2};"

! 3 the subducting slab

write(42,*) "Surface Loop(3) = {"
do iEdge = 1, 4
do iLine = 2, nBendSteps
    write(42,*) iEdge*1000+iLine, ","
enddo
enddo
write(42,*) "1, 31,32,33,34,51,52,53,54,55};"
write(42,*) "Volume(3) = {3};"
write(42,*) "Physical Volume(3) = {3};"

close(42)

end program
