#! /bin/bash

#nnn     = int(sys.argv[1])
#Npicard = int(sys.argv[2])
#niter   = int(sys.argv[3])

nnn=5
niter=30

for Npicard in  2 3 4 5 6 7 9 11 13 15 17 19  21 23 25 27 29 31 ; do
    python3 stone.py $nnn $Npicard $niter
    mv conv.ascii conv_${nnn}_${Npicard}_${niter}.ascii
    mv stats_theta.ascii stats_theta_${nnn}_${Npicard}_${niter}.ascii
done
