#! /bin/bash
#   nelx    nely    visu    niter   bc   eta_m 

niter=25
#nelx=100
#nely=30

nelx=150
nely=45

#########################################

python3 stone.py $nelx $nely 1 $niter  1  20
mkdir results_compression_20
mv *.ascii results_compression_20
mv *.vtu results_compression_20

python3 stone.py $nelx $nely 1 $niter  1  21
mkdir results_compression_21
mv *.ascii results_compression_21
mv *.vtu results_compression_21

python3 stone.py $nelx $nely 1 $niter  1  22
mkdir results_compression_22
mv *.ascii results_compression_22
mv *.vtu results_compression_22

#########################################
# -1 reverses the boundary conditions


python3 stone.py $nelx $nely 1 $niter -1  20
mkdir results_extension_20
mv *.ascii results_extension_20
mv *.vtu results_extension_20

python3 stone.py $nelx $nely 1 $niter -1  21
mkdir results_extension_21
mv *.ascii results_extension_21
mv *.vtu results_extension_21

python3 stone.py $nelx $nely 1 $niter -1  22
mkdir results_extension_22
mv *.ascii results_extension_22
mv *.vtu results_extension_22



