#! /bin/bash

rm errors_*
rm vrms_*
rm *.ascii

for rs in 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 40 48 56 64 80 96 128; do

    echo $rs 

    python3 stone.py $rs $rs 0 > opla

    grep errv opla >> errors
    grep vrms opla >> vrms

done

rm opla
