#! /bin/bash


python3 stone.py 69 69 1 0 > opla0
mv solution.vtu solution0.vtu

python3 stone.py 31 31 1 1 > opla1
mv solution.vtu solution1.vtu

python3 stone.py 20 20 1 2 > opla2
mv solution.vtu solution2.vtu

python3 stone.py 20 20 1 3 > opla3
mv solution.vtu solution3.vtu



