#! /bin/bash

echo 'reg'
python3 stone.py 3 2 1 0 0 > opla
mv solution.vtu solution_0.vtu

echo 'S'
python3 stone.py 3 2 1 1 0 > opla
mv solution.vtu solution_1.vtu

echo 'LT'
python3 stone.py 3 2 1 2 0 > opla
mv solution.vtu solution_2.vtu

echo 'QZ1'
python3 stone.py 3 2 1 3 0 > opla
mv solution.vtu solution_3.vtu

echo 'QZ2'
python3 stone.py 3 2 1 4 0 > opla
mv solution.vtu solution_4.vtu

echo 'QZ3'
python3 stone.py 3 2 1 5 0 > opla
mv solution.vtu solution_5.vtu

echo 'A'
python3 stone.py 3 2 1 6 0 > opla
mv solution.vtu solution_6.vtu

echo 'B'
python3 stone.py 3 2 1 7 0 > opla
mv solution.vtu solution_7.vtu

rm opla
