#! /bin/bash

rm -f errors*
rm opla_*

for l in 1 2 3 4 5 6; do

    for n in 8 16 32 48 64 96 128; do

       echo nelx=nely= $n lambda= $l
       python3 stone.py  $n $n 0 $l > opla
       grep errv opla >> errors$l
       mv conv.ascii conv_${l}_${n}.ascii
       #mv opla opla_${l}_${n}
    done

done
