#! /bin/bash

rm -f errors*
rm opla_*

for l in 2 3 4 ; do

    for n in 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 27 29 32 37 41 44 48 56 64 96 128; do

       echo nelx=nely= $n lambda= $l
       python3 stone.py  $n $n 0 $l > opla
       grep errv opla >> errors$l
       mv conv.ascii conv_${l}_${n}.ascii
       grep int_p opla >> pstats_${l}.ascii
       #mv opla opla_${l}_${n}
    done

done
