#! /bin/bash

rm -f errors*
rm -f stats*

for nq in 2 3 4 5 6 ; do
    for res in {8..80}; do
        echo $res X $res
        python3 stone2D.py $res $res 0 $nq > opla
        grep errv opla >> errors_nq$nq
        grep stats opla >> stats_nq$nq
    done
done

