#! /bin/bash
rm -f errors*
rm -f vrms* 
rm -f area* 

for l in 4 6 8 10 12 14 16 20 24 28 32 40 48 64 80; do

    echo nelr=$l 

    echo 3x3 quadrature
    python3 stone.py $l 0 3 > opla  
    grep errv opla >> errors_3 
    grep vrms opla >> vrms_3
    grep area opla | grep meas >> area_3

    echo 4x4 quadrature
    python3 stone.py $l 0 4 > opla  
    grep errv opla >> errors_4 
    grep vrms opla >> vrms_4 
    grep area opla | grep meas >> area_4

    echo 5x5 quadrature
    python3 stone.py $l 0 5 > opla  
    grep errv opla >> errors_5 
    grep vrms opla >> vrms_5
    grep area opla | grep meas >> area_5

    echo 6x6 quadrature
    python3 stone.py $l 0 6 > opla  
    grep errv opla >> errors_6 
    grep vrms opla >> vrms_6
    grep area opla | grep meas >> area_6

done

rm opla

