#! /bin/bash
#   exp         = int(sys.argv[1])
#   nelr        = int(sys.argv[2])
#   visu        = int(sys.argv[3])
#   nqperdim    = int(sys.argv[4])
#   mapping     = int(sys.argv[5])
#   xi          = int(sys.argv[6])
#   etablobstar = float(sys.argv[7])
#   rhoblobstar = float(sys.argv[8])
#   yblob       = float(sys.argv[9])
#   Rblob       = float(sys.argv[10])
#   etalithstar = float(sys.argv[11])
#   compute_g   = int(sys.argv[12])
#   nel_phi     = int(sys.argv[13])

rm errors_*
rm vrms_* 
rm u_err_*
rm v_err_*
rm p_err_*

xi=6
l=64

for nelphi in 16 32 64 128 192 256 384 ; do
  for nqperdim in 3 4 5  ; do
    for mapping in  3 4 5 ; do

      echo nqperdim= $nqperdim - mapping= $mapping - nel_phi= $nelphi

      # exp1 - aquarium
      #python3 stone.py 1 $l 0 $nqperdim $mapping $xi 1 1 0 0 1 1 $nelphi > opla

      # exp2 - blob
      python3 stone.py 2 $l 0 $nqperdim $mapping $xi 1 0.999 4900000 400000 1 1 $nelphi > opla

      mv gravity_0000.ascii gravity_nq${nqperdim}_m${mapping}_nelphi${nelphi}.ascii 

    done
  done
done
