#! /bin/bash
#   exp         = int(sys.argv[1])
#   nelr        = int(sys.argv[2])
#   visu        = int(sys.argv[3])
#   nqperdim    = int(sys.argv[4])
#   mapping     = int(sys.argv[5])
#   xi          = int(sys.argv[6])
#   etablobstar = float(sys.argv[7])
#   rhoblobstar = float(sys.argv[8])
#   yblob       = float(sys.argv[9])
#   Rblob       = float(sys.argv[10])
#   etalithstar = float(sys.argv[11])

for l in 8 10 12 16 24 32 40 48 64 ; do
   for nqperdim in 3 4 5 6 7 ; do
      for mapping in 1 2 3 4 5 6; do
          for xi in 6 ; do

              echo nelr= $l - nqperdim= $nqperdim - mapping= $mapping - xi= $xi

              python3 stone.py -1 $l 0 $nqperdim $mapping $xi 1 1 0 0 1 > opla

              grep area opla | grep meas >> area_${nqperdim}_${mapping}
              grep volume opla | grep meas >> volume_${nqperdim}_${mapping}

         done
      done
   done
done

