#!/bin/bash

rm -f stat_*.ascii
rm -f errors_*.ascii

etab=100

#----------------------------------------------------

for mapped in 0 1; do
    for pdisc in 0 1; do
        for curved in 0 1; do
            echo ++++++++++++++++++++++++++++++++++++++++++++++++
            mkdir curved${curved}_pdisc${pdisc}_mapped${mapped}
            #for n in  21 22 23 24 25 26 27 28 29 32 36 40 42 45 48 51 54 56 58 61 64 69 72 77 80 85 88 93 96 128; do 
            for n in  16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 32 48 64 ; do 
                echo resolution: $n curved: $curved pdisc: $pdisc mapped: $mapped
                python3 stone.py $n $n 0 $etab $curved $pdisc $mapped > opla
                grep benchmark opla  >> stats_curved${curved}_pdisc${pdisc}_mapped${mapped}.ascii
                grep errv opla  >> errors_curved${curved}_pdisc${pdisc}_mapped${mapped}.ascii
            done
            mv *.ascii curved${curved}_pdisc${pdisc}_mapped${mapped}
            mv *.vtu curved${curved}_pdisc${pdisc}_mapped${mapped}
        done
    done
done

rm opla


