#! /bin/bash

# um c o fu fd res width

python3 stone.py 20 22 23 0 2  200  100
mv solution_surface.ascii solution_surface_20_22_23_000_200.ascii
mv solution.vtu solution_20_22_23_000_200.vtu

python3 stone.py 20 22 23 0.5 1.5  200  100
mv solution_surface.ascii solution_surface_20_22_23_050_150.ascii
mv solution.vtu solution_20_22_23_050_150.vtu

python3 stone.py 20 22 23 1 1  200  100
mv solution_surface.ascii solution_surface_20_22_23_100_100.ascii
mv solution.vtu solution_20_22_23_100_100.vtu

python3 stone.py 20 22 23 1.5 0.5 200  100
mv solution_surface.ascii solution_surface_20_22_23_150_050.ascii
mv solution.vtu solution_20_22_23_150_050.vtu

python3 stone.py 20 22 23 2 0 200  100
mv solution_surface.ascii solution_surface_20_22_23_200_000.ascii
mv solution.vtu solution_20_22_23_200_000.vtu
