#! /bin/bash

# um c=22 o fu fd res width 

python3 stone.py 19 22 22 1 1 200  100
mv solution_surface.ascii solution_surface_19_22_22.ascii
mv solution.vtu solution_19_22_22.vtu

python3 stone.py 19 22 23 1 1 200  100
mv solution_surface.ascii solution_surface_19_22_23.ascii
mv solution.vtu solution_19_22_23.vtu

python3 stone.py 19 22 24 1 1 200  100
mv solution_surface.ascii solution_surface_19_22_24.ascii
mv solution.vtu solution_19_22_24.vtu

#-----------------------------------------

python3 stone.py 20 22 22 1 1 200  100
mv solution_surface.ascii solution_surface_20_22_22.ascii
mv solution.vtu solution_20_22_22.vtu

python3 stone.py 20 22 23 1 1 200  100
mv solution_surface.ascii solution_surface_20_22_23.ascii
mv solution.vtu solution_20_22_23.vtu

python3 stone.py 20 22 24 1 1 200  100
mv solution_surface.ascii solution_surface_20_22_24.ascii
mv solution.vtu solution_20_22_24.vtu

#-----------------------------------------
