#! /bin/bash

visu=0
bench=2
tol_nl=0.000001
psi=0 
niter=10 
eta_v=24

for nelx in 64 ; do
    for phi in 0 10 20 30 ; do
        for eta_m in 0 21 ; do
            echo ${nelx}_${phi} 
            python3 stone.py $nelx $visu $bench $phi $psi $niter $tol_nl $eta_v $eta_m > opla
            mkdir benchmark2_${nelx}_${phi}_${eta_m}
            mv *.ascii benchmark2_${nelx}_${phi}_${eta_m}
            mv *.vtu benchmark2_${nelx}_${phi}_${eta_m}
        done
    done
done

rm opla

