#! /bin/bash

rm -f errors.ascii

for n in 8 10 12 14 16 18 20 22 24 28 32 36 40 44 48 52 56 60 64 80 96 ; do
    echo nelx=nely= $n
    python3 stone.py  $n  $n 0 | grep errv >> errors.ascii
done

#for n in 7 9 11 13 15 17 19 21 23 25 27 29 31 33; do
#    echo nelx=nely= $n
#    python3 stone.py  $n  $n 0 | grep errv >> errors.ascii
#done

