#! /bin/bash

# nelx=int(sys.argv[1])
# nely=int(sys.argv[2])
# visu=int(sys.argv[3])
# nqperdim=int(sys.argv[4])
# meth=int(sys.argv[5])
# center=int(sys.argv[6])
# mesh_type=int(sys.argv[7])
# straight_edges
# benchmark nb

rm errors_*
rm vrms_*
rm *.ascii

nq=3

for b in 1 3 4 9; do
    for mt in 1 2 3 4 5 6; do 
        for c in 0; do 
            for m in 1 2 ; do
                for rs in 4 6 8 12 16 24 32 48 64 96 128 160 192 256; do

                   echo mesh_type=$mt center=$c method=$m res=$rs 

                   python3 stone.py $rs $rs 0 $nq $m $c $mt 1 $b > opla

                   grep errv opla >> errors_mt${mt}_center${c}_meth$m
                   #grep vrms opla >> vrms_mt${mt}_center${c}_meth$m
    
                done
            done
        done
    done
    mkdir bench${b}
    mv errors* bench${b}
done

rm opla
