#! /bin/bash

# nelx=int(sys.argv[1])
# nely=int(sys.argv[2])
# visu=int(sys.argv[3])
# nqperdim=int(sys.argv[4])
# meth=int(sys.argv[5])
# center=int(sys.argv[6])
# mesh_type=int(sys.argv[7])
# straight_edges

rm errors_*
rm vrms_*
rm *.ascii

nq=3

for mt in 2 3 4 5; do 
    for c in 0 1 2 3; do 
        for m in 1 2 ; do
            for rs in 4 6 8 12 16 24 32 48 64 96 128; do

               echo mesh_type=$mt center=$c method=$m res=$rs 

               python3 stone.py $rs $rs 0 $nq $m $c $mt 0 > opla

               grep errv opla >> errors_mt${mt}_center${c}_meth$m
               grep vrms opla >> vrms_mt${mt}_center${c}_meth$m

            done
        done
    done
done

rm opla
