#! /bin/bash

rm errors_*
rm vrms_*
rm *.ascii

for nq in 2 3 4 ; do

    for rs in 4 5 6 7 8 9 10 11 12 13 14 15 16 20 24 32 40 43 48; do

        echo $rs 

        python3 stone.py $rs $rs 0 $nq > opla

        grep errv opla >> errors_nq$nq
        grep vrms opla >> vrms_nq$nq

    done

done

rm opla
