#! /bin/bash

rm errors_*
rm vrms_*
rm *.ascii

for m in 1 2 ; do

   for nq in 2 3 4 ; do
 
       for rs in 4 5 6 7 8 9 10 12 14 16 20 24 32 40 48 64; do

           echo res=$rs nq=$nq method=$m  

           python3 stone.py $rs $rs 0 $nq $m > opla

           grep errv opla >> errors_nq${nq}_meth$m
           grep vrms opla >> vrms_nq${nq}_meth$m

       done

    done

done

rm opla
