#!/bin/bash

rm errors_*.ascii
   
for nstep in 32 48 64 80 96 112 128 160 192 200 256 300 384 400 512 600 700 800 900 1024 1500 2048; do

    for method in RK1 RK2 RK3 RK4 RK4_38 RKF ODE87 ; do

      echo method= $method nstep= $nstep

      python3 stone.py 192 $nstep  $method 0 > opla

      grep err opla >> errors_${method}.ascii

   done

done



