#!/bin/bash

rm statistics*.ascii
rm errors*.ascii
rm solve*.ascii
rm time_per_iteration_*.ascii

nq=3

#for res in 8 9 10 11 12 13 14 15 16 18 19 20 21 22 23 24 26 28 30 32 36 40 44 48 52 56 64 72 80 96 112 128 144 160 192; do
for res in 8 10 16 24 32 40 48 64 80 96 128; do

    echo mesh $res x $res  

    for solver in  22 ; do 

        echo -solver=$solver

        python3 stone.py $res $res 0 $nq $solver > opla

        grep errv opla >> errors_${solver}.ascii
        grep bench opla >> statistics_${solver}.ascii
        grep solve opla >> solve_${solver}.ascii
        grep iteration opla >> time_per_iteration_${solver}.ascii
        if [ $solver -eq 4 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 13 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 14 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 15 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 16 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 18 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 19 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 20 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 21 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 22 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi




    done

done
