#!/bin/bash

nq=3
res=32

rm popo

for solver in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 ; do 

    #echo -solver=$solver

    python3 stone.py $res $res 0 $nq $solver > opla

    grep errv opla >> popo

done
