#!/bin/bash

rm errors*.ascii
rm solve*.ascii
rm time_per_iteration_*.ascii

nq=3

for res in 16 24 32 40 48 64 80 96 128 160 192 256; do

    echo mesh $res x $res  

    for solver in 1 14 23 ; do 

        echo ---- solver=$solver

        python3 stone.py $res $res 0 $nq $solver > opla 

        grep errv opla >> errors_${solver}.ascii

        grep solve opla | grep time >> solve_${solver}.ascii

        grep iteration opla >> time_per_iteration_${solver}.ascii
        if [ $solver -eq 4 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 13 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 14 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 15 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 16 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 18 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 19 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 20 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 21 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 22 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi
        if [ $solver -eq 23 ] 
        then
           mv solver_convergence.ascii solver_convergence_${solver}_${res}.ascii
        fi

    done

done
