#!/bin/bash

rm statistics*.ascii
rm errors*.ascii
rm solve*.ascii

nq=3

for res in 8 12 16 20 24 28 32 40 48 56 64; do

    for solver in 4 ; do 

        echo $res x $res  solver=$solver

        python3 stone.py $res $res 0 $nq $solver > opla

        grep errv opla >> errors_${solver}.ascii
        grep bench opla >> statistics_${solver}.ascii
        grep solve opla >> solve_${solver}.ascii

    done

done
