#!/bin/bash

rm statistics*.ascii
rm errors*.ascii
rm solve*.ascii

nq=3
solver=14

for res in 8 12 16 20 24 28 32 40 48 56 64 96 112 116 120 124 128 136 144 152 160 168 176 184 192 200 256 300 400; do

#for res in {8..112} ; do

    echo $res x $res  solver=$solver

    python3 stone.py $res $res 0 $nq $solver > opla

    grep errv opla >> errors.ascii
    grep bench opla >> statistics.ascii
    grep solve opla >> solve.ascii


done
