#! /bin/bash

rm errors*.ascii
rm vrms*.ascii

for sft in 1 2; do
    for form in  1 2 ; do
        for rs in 4 5 6 7 8 9 10 11 12  14  16 32 48 64; do
            echo sft=$sft form=$form rs=$rs

            python3 stone.py $rs $rs $rs $sft $form > opla
            grep errv opla >> errors_sft${sft}_form${form}.ascii
            grep vrms opla >> vrms_sft${sft}_form${form}.ascii

        done
    done
done

rm opla


