#! /bin/bash

rm opla
rm vrms_stretch*
rm Twedge_stretch*
rm Tavrg_stretch*
rm Tslab_stretch*
rm Tcorner_stretch*


nelx=66
nely=60

for sl in 0.4 0.42 0.44 0.46 0.48 0.5 0.52 0.54 0.56 0.58 0.6 0.65 0.7 0.75 0.8 0.9 1  ; do
    echo $sl
    python3 stone.py $nelx $nely 0 $sl > opla
    grep Twedge opla >> Twedge_stretch_${nelx}x${nely}
    grep Tavrg opla >> Tavrg_stretch_${nelx}x${nely}
    grep Tslab opla >> Tslab_stretch_${nelx}x${nely}
    grep Tcorner opla >> Tcorner_stretch_${nelx}x${nely}
    grep vrms opla >> vrms_stretch_${nelx}x${nely}

done


