#! /bin/bash

rm *.ascii

nstep=100

for res in 16 24 32 40 48 56 64; do

    for R in 10000 100000 1000000; do

        echo res= $res - Ra= $R - order=2
        python3 stone.py  $res $res 0 2 $R $nstep > opla_${R}_${res}
        mv Nu_vrms.ascii Nu_vrms_$R.Q2_$res.ascii
        mv T_profile.ascii T_profile_$R.Q2_$res.ascii
    done

done





