#! /bin/bash

rm onset*.ascii

nstep=5

for R in 770 771 772 773 774 775 776 777 778 779 780 ; do

    for res in 48; do

        echo Ra= $R - resolution $res 
        python3 stone_new.py  $res $R $nstep | grep script >> onset_${res}x${res}.ascii
        mv Nu_vrms.ascii Nu_vrms_${R}_${res}x${res}.ascii

    done

done

