#! /bin/bash
rm -f errors_*
rm -f middle_*
rm opla

t=0

for e in 1 2 3 4 5; do
    echo ========element= $e =======================
    echo 8x8
    python3 stone.py   8   8 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 12x12
    python3 stone.py  12  12 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 16x16
    python3 stone.py  16  16 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 24x24
    python3 stone.py  24  24 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 32x32
    python3 stone.py  32  32 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 48x48
    python3 stone.py  48  48 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 64x64
    python3 stone.py  64  64 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 96x96
    python3 stone.py  96  96 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 128x128
    python3 stone.py 128 128 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 192x192
    python3 stone.py 192 192 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 256x256
    python3 stone.py 256 256 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
    echo 320x320
    python3 stone.py 320 320 0 $e $t > opla
    grep errv opla >> errors_$e
    grep middle opla >> middle_$e
done





