#! /bin/bash

for res in 64 96 128 160 192 256 400; do

    echo nelx= $res 

    python3 stone.py $res > opla

    mv xprofile.ascii xprofile_${res}.ascii
    mv zprofile.ascii zprofile_${res}.ascii
    mv solution.vtu solution_${res}.vtu

done

