#! /bin/bash

rm statistics*.ascii
rm vrms*.ascii
rm errors*.ascii

for res in {4..16}; do

    for nq in 1 2 3; do

        echo $res x $res x $res nq= $nq

        python3 stoneQ2Q0.py $res 0 $nq > opla

        grep bench opla >> statistics_$nq.ascii  
        grep errv opla >> errors_$nq.ascii
        grep vrms opla >> vrms_$nq.ascii

    done

done

