#! /bin/bash

rm statistics.ascii
rm vrms.ascii
rm errors.ascii

#for res in {4..16}; do
for res in 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 28 32 ; do

    echo $res x $res x $res

    python3 stone.py $res > opla

    grep bench opla >> statistics.ascii  
    grep errv opla >> errors.ascii
    grep vrms opla >> vrms.ascii

done

