#! /bin/bash

rm statistics.ascii
rm vrms.ascii
rm errors.ascii
rm solve.ascii
rm solve_stats.ascii
rm build.ascii

for res in {4..32}; do

    for l in {1..5}; do

        echo $res x $res x $res

        julia stone.jl $res 0 > opla

        grep gc opla >> solve_stats.ascii
        grep solve opla >> solve.ascii
        grep build opla >> build.ascii

    done

    grep bench opla >> statistics.ascii  
    grep errv opla >> errors.ascii
    grep vrms opla >> vrms.ascii

done
