#! /bin/bash

rm statistics.ascii

#for res in {4..16}; do
for res in 4 5 6 7 8 10 12 15 16 20 24 ; do

    echo $res x $res x $res

    python3 stone.py $res > opla

    grep bench opla >> statistics.ascii  

done

