#! /bin/bash

rm *.ascii 

for n in {8..24} ; do
    echo nelx=nely=nelz= $n 
    python3 stone.py  $n $n $n 0 > opla
    grep Build opla >> build.ascii
    grep Solve opla >> solve.ascii
    grep assemb opla >> assembly.ascii
    grep quad opla >> quad.ascii
done

