#! /bin/bash

rm -f errors3
rm -f errors6
rm -f errors7

for n in {8..32} ; do
    echo nelx=nely= $n
    python3 stone.py  $n $n 0 3 | grep errv >> errors3
    python3 stone.py  $n $n 0 6 | grep errv >> errors6
    python3 stone.py  $n $n 0 7 | grep errv >> errors7
done

echo nelx=nely= 32
python3 stone.py  32  32 0 3 | grep errv >> errors3
python3 stone.py  32  32 0 6 | grep errv >> errors6
python3 stone.py  32  32 0 7 | grep errv >> errors7

echo nelx=nely= 36
python3 stone.py  36  36 0 3 | grep errv >> errors3
python3 stone.py  36  36 0 6 | grep errv >> errors6
python3 stone.py  36  36 0 7 | grep errv >> errors7

echo nelx=nely= 40
python3 stone.py  40  40 0 3 | grep errv >> errors3
python3 stone.py  40  40 0 6 | grep errv >> errors6
python3 stone.py  40  40 0 7 | grep errv >> errors7

echo nelx=nely= 48
python3 stone.py  48  48 0 3 | grep errv >> errors3
python3 stone.py  48  48 0 6 | grep errv >> errors6
python3 stone.py  48  48 0 7 | grep errv >> errors7

echo nelx=nely= 64
python3 stone.py  64  64 0 3 | grep errv >> errors3
python3 stone.py  64  64 0 6 | grep errv >> errors6
python3 stone.py  64  64 0 7 | grep errv >> errors7

echo nelx=nely= 80
python3 stone.py  80  80 0 3 | grep errv >> errors3
python3 stone.py  80  80 0 6 | grep errv >> errors6
python3 stone.py  80  80 0 7 | grep errv >> errors7

echo nelx=nely= 90
python3 stone.py  90  90 0 3 | grep errv >> errors3
python3 stone.py  90  90 0 6 | grep errv >> errors6
python3 stone.py  90  90 0 7 | grep errv >> errors7

