#! /bin/bash

rm -f errors
rm -f build_0.ascii
rm -f build_1.ascii
rm -f solve_0.ascii
rm -f solve_1.ascii
rm -f Ael_0.ascii
rm -f Ael_1.ascii

for s in 0.03 0.029 0.028 0.027 0.026 0.025 0.024 0.023 0.022 0.021 0.02 0.019 0.018 0.017 0.016 0.015 0.014 0.013 0.012 0.011 0.01 0.009 0.008 0.007 0.006 0.005 0.004 0.003 0.002 0.001 0.0007 0.0006 0.0005 0.0004 0.0003 0.0002 0.0001 ; do
    for m in 0 1 ; do 
        echo  $m $s
        python3 stone.py $m $s > opla 
        #grep errv opla >> errors
        grep Build opla >> build_${m}.ascii 
        grep Solve opla >> solve_${m}.ascii 
        grep Ael opla >> Ael_${m}.ascii 
    done
done
