#! /bin/bash

rm timings_solve_V6
rm timings_build_V6
rm timings_errors_V6
rm timings_normalise_V6
rm errors_V6

for n in {8..48} ; do
    for s in {1..5} ; do 
        echo nelx=nely= $n
        python3 stone_V6.py  $n > opla
        grep solve opla >> timings_solve_V6
        grep FE opla >> timings_build_V6
        grep errors opla >> timings_errors_V6
        grep normalise opla >> timings_normalise_V6
        grep errv opla >> errors_V6
    done
done

for n in 52 56 60 64 68 72 80 96 112 128 ; do
    for s in {1..5} ; do 
        echo nelx=nely= $n
        python3 stone_V6.py  $n > opla
        grep solve opla >> timings_solve_V6
        grep FE opla >> timings_build_V6
        grep errors opla >> timings_errors_V6
        grep normalise opla >> timings_normalise_V6
        grep errv opla >> errors_V6
    done
done




