#!/bin/bash

rm *.ascii

visc2=1e21
lambda=256e3

for n in 16 32 48 ; do 

    for a in 1 2 3; do 

        echo n= $n assembly= $a

        python3 stone.py $n $n  0 $lambda 3000 $visc2 > opla

        grep bc opla >> bc_${a}.ascii 
        grep assembl opla >> assembly_${a}.ascii 
        grep build opla >> build_${a}.ascii 
        grep convert opla >> convert_${a}.ascii 
        grep solve opla >> solve_${a}.ascii 

    done

done

rm opla
