#! /bin/bash

rm results_*
rm *.ascii

for rho2 in 3208 3232 3328 ; do

for eta1 in  20 21 22  ; do

for eta2 in 18 18.5 19 19.5 20 20.5 21 21.5 22 22.5 23 23.5 24 ; do

        echo $rho2 $eta1 $eta2

        python3 fieldstone.py 64 64 0 0 $rho2 $eta1 $eta2 > opla

        grep vblock opla >> results_$rho2

done
done
done

rm opla

