#!/bin/bash

rm -f errors.ascii
rm -f errors_sr1.ascii
rm -f errors_sr2.ascii
rm -f errors_sr3.ascii
rm -f vrms.ascii

#for l in 4 6 8 10 12 14 16 20 24 32 36 40 44 48 56 64 72 80; do
for l in 6 8 10 12 14 16 ; do

   echo nelr= $l

   python3 stone.py $l 0 > opla  
   grep errv opla >> errors.ascii 
   grep vrms opla >> vrms.ascii 
   grep errexx1 opla >> errors_sr1.ascii
   grep errexx2 opla >> errors_sr2.ascii
   grep errexx3 opla >> errors_sr3.ascii

done

rm opla
