#!/bin/bash

rm opla*
rm vrms*
rm errors* 

###############################################################################
# 22
###############################################################################
Vspace=P1
Pspace=P0

echo ---------- $Vspace X $Pspace ----------

for nqpts in  6 7 12; do
    for n in 8 12 16 24 25 32 40 48 56 64 80 96 112 128 144 160; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

