#!/bin/bash

#for n in 20 25 30 35 40 50 60 70 80 90 100 120 140 160 180 200 250 300; do

mkdir paperresults

###############################################################################
# solcx
###############################################################################

echo =================solcx====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solcx
mkdir paperresults/solcx/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solcx 0 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/solcx/structured
mv opla* paperresults/solcx/structured
mv vrms* paperresults/solcx/structured
#mv *.vtu paperresults/solcx/structured
#mv *.ascii paperresults/solcx/structured

echo =================solcx====================unstructured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solcx
mkdir paperresults/solcx/unstructured

for e in 3 5 9 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solcx 1 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/solcx/unstructured
mv opla* paperresults/solcx/unstructured
mv vrms* paperresults/solcx/unstructured
#mv *.vtu paperresults/solcx/unstructured
#mv *.ascii paperresults/solcx/unstructured




###############################################################################
# solvi
###############################################################################

echo =================solvi====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solvi
mkdir paperresults/solvi/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solvi 0 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}
done

mv err* paperresults/solvi/structured
mv opla* paperresults/solvi/structured
mv vrms* paperresults/solvi/structured
mv solvi_p_* paperresults/solvi/structured
#mv *.vtu paperresults/solvi/structured
#mv *.ascii paperresults/solvi/structured

echo =================solvi====================unstructured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solvi
mkdir paperresults/solvi/unstructured

for e in 3 5 9 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solvi 1 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/solvi/unstructured
mv opla* paperresults/solvi/unstructured
mv vrms* paperresults/solvi/unstructured
mv solvi_p_* paperresults/solvi/unstructured
#mv *.vtu paperresults/solvi/unstructured
#mv *.ascii paperresults/solvi/unstructured




















###############################################################################
#donea & huerta
###############################################################################

echo =================dh====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/dh
mkdir paperresults/dh/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace dh 0 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/dh/structured
mv opla* paperresults/dh/structured
mv vrms* paperresults/dh/structured
#mv *.vtu paperresults/dh/structured
#mv *.ascii paperresults/dh/structured

echo =================dh====================unstructured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/dh
mkdir paperresults/dh/unstructured

for e in 3 5 9 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace dh 1 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/dh/unstructured
mv opla* paperresults/dh/unstructured
mv vrms* paperresults/dh/unstructured
#mv *.vtu paperresults/dh/unstructured
#mv *.ascii paperresults/dh/unstructured































###############################################################################
# solkz
###############################################################################

echo =================solkz====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solkz
mkdir paperresults/solkz/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solkz 0 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/solkz/structured
mv opla* paperresults/solkz/structured
mv vrms* paperresults/solkz/structured
#mv *.vtu paperresults/solkz/structured
#mv *.ascii paperresults/solkz/structured

echo =================solkz====================unstructured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solkz
mkdir paperresults/solkz/unstructured

for e in 3 5 9 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 20 30 40 50 60 70 80 90 100; do
        echo mesh: $n X $n 
        python3 stone.py $n $Vspace $Pspace solkz 1 >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/solkz/unstructured
mv opla* paperresults/solkz/unstructured
mv vrms* paperresults/solkz/unstructured
#mv *.vtu paperresults/solkz/unstructured
#mv *.ascii paperresults/solkz/unstructured































