#!/bin/bash

###############################################################################
# solvi
###############################################################################

echo =================solvi====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/solvi
mkdir paperresults/solvi/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 16 20 24 28 32 36 40 44 48 56 64 72 80 88 96 104 112 128 160 256; do
        echo mesh: $n X $n 
        start=`date +%s.%N`
        python3 stone.py $n $Vspace $Pspace solvi 0 >> opla
        end=`date +%s.%N`
        runtime=$( echo "$end - $start" | bc -l )
        echo '     -> ' $runtime ' s'
        mv visu_V.vtu visu_V_${Vspace}_${Pspace}_${n}.vtu
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}
done

mv err* paperresults/solvi/structured
mv opla* paperresults/solvi/structured
mv vrms* paperresults/solvi/structured
mv solvi_p_* paperresults/solvi/structured
mv visu*.vtu paperresults/solvi/structured
#mv *.ascii paperresults/solvi/structured

