#!/bin/bash

rm opla*
rm vrms*
rm errors* 

###############################################################################
# 4
###############################################################################
Vspace=Q2
Pspace=Q-1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 9 12 13 16 17 24 25 32 33 40 41 48 49 56 64 80 96 112 128; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done
