#!/bin/bash

rm opla*
rm vrms*
rm errors* 

#exp=1: single 16x16 resolution, default nqpt
#exp=2: 8x8, 16x16, 32x32 resolutions, default nqpt
#exp=3: all between 8 and 192, default nqpt
#exp=4: 8,16,32,64,96  3 different nqpt values

exp=4


for e in {1..27}; do

#for e in {26..27}; do

    #--------------
    if test $e == 1  ; then Vspace=Q1    Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 2  ; then Vspace=Q2    Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 3  ; then Vspace=P2    Pspace=P0    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 6  ; then Vspace=Q3    Pspace=Q2    nq1=3  nq2=3  nq3=5 ; fi
    if test $e == 7  ; then Vspace=P3    Pspace=P2    nq1=6  nq2=7  nq3=12; fi
    if test $e == 8  ; then Vspace=Q1+   Pspace=Q1    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 10 ; then Vspace=RT1   Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 11 ; then Vspace=RT2   Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 12 ; then Vspace=DSSY1 Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 13 ; then Vspace=DSSY2 Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 14 ; then Vspace=Han   Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1   nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 16 ; then Vspace=Q2    Pspace=Pm1u  nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 17 ; then Vspace=Q2s   Pspace=Q1    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1   nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 19 ; then Vspace=P2+   Pspace=P1    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 20 ; then Vspace=P2    Pspace=P1+P0 nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 21 ; then Vspace=P1NC  Pspace=P0    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 22 ; then Vspace=P1    Pspace=P0    nq1=3  nq2=6  nq3=7 ; fi
    if test $e == 23 ; then Vspace=Q2    Pspace=Q-1   nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 24 ; then Vspace=Q2    Pspace=Q1+Q0 nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 25 ; then Vspace=Chen  Pspace=Q0    nq1=2  nq2=3  nq3=4 ; fi
    if test $e == 26 ; then Vspace=Q4    Pspace=Q3    nq1=5  nq2=6  nq3=7 ; fi
    if test $e == 27 ; then Vspace=P4    Pspace=P3    nq1=12 nq2=13 nq3=16; fi

    echo $n ---------- $Vspace X $Pspace ----------

    if test $exp == 1; then
       echo mesh: 16 X 16 
       python3 stone.py 16 16 $Vspace $Pspace -1 >> opla
       grep errv opla 
       mv opla opla_${Vspace}x${Pspace}
    fi 

    if test $exp == 2; then
       for n in 8 16 32 ; do
           echo mesh: $n X $n 
           python3 stone.py $n $n $Vspace $Pspace -1 >> opla
       done
       grep errv opla > errors_${Vspace}x${Pspace}
       grep vrms= opla > vrms_${Vspace}x${Pspace}
       mv opla opla_${Vspace}x${Pspace}
    fi 

    if test $exp == 3; then
       for n in 8 9 10 11 12 16 24 32 40 48 56 64 80 96 112 128 160 192; do
           echo mesh: $n X $n 
           python3 stone.py $n $n $Vspace $Pspace -1 >> opla
       done
       grep errv opla > errors_${Vspace}x${Pspace}
       grep vrms= opla > vrms_${Vspace}x${Pspace}
       mv opla opla_${Vspace}x${Pspace}
    fi 

    if test $exp == 4; then
       for nqpts in  $nq1 $nq2 $nq3 ; do
           for n in 8 16 32 64 96 ; do
               echo mesh: $n X $n - nqpts: $nqpts
               python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
           done
           grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
           grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
           mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
       done
    fi

done


