#!/bin/bash

# sudo apt-get install bc

###############################################################################
#donea & huerta
###############################################################################

echo =================johnbook====================structured
rm -f opla*
rm -f vrms*
rm -f errors* 
mkdir paperresults/johnbook
mkdir paperresults/johnbook/structured

for e in 3 4 5 9 15 18 ; do 

    if test $e == 3  ; then Vspace=P2    Pspace=P0  ; fi
    if test $e == 4  ; then Vspace=Q2    Pspace=Q1  ; fi
    if test $e == 5  ; then Vspace=P2    Pspace=P1  ; fi
    if test $e == 9  ; then Vspace=P1+   Pspace=P1  ; fi
    if test $e == 15 ; then Vspace=Q2    Pspace=Pm1 ; fi
    if test $e == 18 ; then Vspace=P2+   Pspace=P-1 ; fi

    echo ---------- $Vspace X $Pspace ----------

    for n in 16 24 32 40 48 56 64 80 96 128 160; do
        echo mesh: $n X $n 
        start=`date +%s.%N`
        python3 stone.py $n $Vspace $Pspace johnbook 0 >> opla
        end=`date +%s.%N`
        runtime=$( echo "$end - $start" | bc -l )
        echo '     -> ' $runtime ' s'
    done
    grep errv opla > errors_${Vspace}_${Pspace}
    grep vrms= opla > vrms_${Vspace}_${Pspace}
    mv opla opla_${Vspace}_${Pspace}

done

mv err* paperresults/johnbook/structured
mv opla* paperresults/johnbook/structured
mv vrms* paperresults/johnbook/structured
