#!/bin/bash

rm opla*
rm vrms*
rm errors* 

./script_run_Q1Q0    # 1
./script_run_Q2Q0    # 2
./script_run_P2P0    # 3
./script_run_Q2Q1    # 4
./script_run_P2P1    # 5
./script_run_Q3Q2    # 6
./script_run_P3P2    # 7
./script_run_Q1+Q1   # 8
./script_run_P1+P1   # 9
./script_run_RT1Q0   #10
./script_run_RT2Q0   #11
./script_run_DSSY1Q0 #12
./script_run_DSSY2Q0 #13
./script_run_HanQ0   #14
./script_run_Q2Pm1   #15
./script_run_Q2Pm1u  #16
./script_run_Q2sQ1   #17
./script_run_P2+P-1  #18
./script_run_P2+P1   #19

