#!/bin/bash

rm opla*
rm vrms*
rm errors* 

###############################################################################
# 1
###############################################################################
Vspace=Q1
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 2
###############################################################################
Vspace=Q2
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 5; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 3
###############################################################################
Vspace=P2
Pspace=P0

echo ---------- $Vspace X $Pspace ----------

for nqpts in  3 6 7 12; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 4
###############################################################################
Vspace=Q2
Pspace=Q1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 5
###############################################################################
Vspace=P2
Pspace=P1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  3 6 7 12; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 6
###############################################################################
Vspace=Q3
Pspace=Q2

echo ---------- $Vspace X $Pspace ----------

for nqpts in  3 4 5; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 7
###############################################################################
Vspace=P3
Pspace=P2

echo ---------- $Vspace X $Pspace ----------

for nqpts in 6 7 12 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 8
###############################################################################
Vspace=Q1+
Pspace=Q1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 5 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 9
###############################################################################
Vspace=P1+
Pspace=P1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  3 6 7 12; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 10
###############################################################################
Vspace=RT1
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in 2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 11
###############################################################################
Vspace=RT2
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in 2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 12
###############################################################################
Vspace=DSSY1
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in 2 3 4 5; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 13
###############################################################################
Vspace=DSSY2
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in 2 3 4 5; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done


###############################################################################
# 14
###############################################################################
Vspace=Han
Pspace=Q0

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 15
###############################################################################
Vspace=Q2
Pspace=Pm1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 16
###############################################################################
Vspace=Q2
Pspace=Pm1u

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 5; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 17
###############################################################################
Vspace=Q2s
Pspace=Q1

echo ---------- $Vspace X $Pspace ----------

for nqpts in  2 3 4 ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 18
###############################################################################
Vspace=P2+
Pspace=P-1

echo ---------- $Vspace X $Pspace ----------

for nqpts in 6 7 12  ; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done

###############################################################################
# 19
###############################################################################
Vspace=P2+
Pspace=P1

echo ---------- $Vspace X $Pspace ----------

for nqpts in 6 7 12; do
    for n in 8 16 32 64 128 192  ; do
        echo mesh: $n X $n - nqpts: $nqpts
        python3 stone.py $n $n $Vspace $Pspace $nqpts >> opla
    done
    grep errv opla > errors_${Vspace}_${Pspace}_nqpts$nqpts
    grep vrms= opla > vrms_${Vspace}_${Pspace}_nqpts$nqpts
    mv opla opla_${Vspace}_${Pspace}_nqpts$nqpts
done
