#! /bin/bash

#   R_inner=float(sys.argv[1]), R_outer=float(sys.argv[2])
#   R_12=float(sys.argv[3]), R_23=float(sys.argv[4]), R_34=float(sys.argv[5]), R_45=float(sys.argv[6])
#   rho1=float(sys.argv[7]), rho2=float(sys.argv[8]), rho3=float(sys.argv[9]), rho4=float(sys.argv[10]), rho5=float(sys.argv[11])
#   eta1=float(sys.argv[12]), eta2=float(sys.argv[13]), eta3=float(sys.argv[14]), eta4=float(sys.argv[15]), eta5=float(sys.argv[16])
#   R_blob=float(sys.argv[17]), eccentricity=float(sys.argv[18]), rho_blob=float(sys.argv[19]), eta_blob=float(sys.argv[20]), depth_blob=float(sys.argv[21])
#   solve_stokes=(int(sys.argv[22])==1), compute_gravity=(int(sys.argv[23])==1)
#   nstep=int(sys.argv[24]), hhh=float(sys.argv[25])
#   element=sys.argv[26]

echo --------------------------- 
echo --------- test  -----------
echo ---------------------------

#for elt in 1 2 3; do
for elt in 1 ; do
   
     echo elt= $elt

    for hh in 200e3 175e3 150e3 125e3 100e3 75e3 50e3 25e3; do
    #for hh in 200e3 ; do

        echo ---hh= $hh

        python3 stone.py 3000e3 6000e3 \
                         5900e3 5700e3 5300e3 3500e3\
                         3000 3000 3000 3000 3000 \
                         1e22 1e22 1e22 1e22 1e22\
                         400e3 0 2999 1e25 1500e3 \
                         1 0 \
                         1 $hh $elt > opla

        grep vrms opla | grep nel   >> test_vrms_${elt}
        grep vol opla  | grep error >> test_volume_${elt}
        grep stats opla             >> test_stats_${elt}
        grep avrg_p_cmb opla        >> test_avrg_p_cmb_${elt}

        mv solution_0000.vtu solution_${hh}_${elt}.vtu
        mv opla opla_${hh}_${elt}
        mkdir surface
        mv surface*.ascii surface/
        mv surface surface_${hh}_${elt}
        mkdir cmb 
        mv cmb*.ascii cmb/
        mv cmb cmb_${hh}_${elt}
 
    done

done
