#! /bin/bash


for e in 0.000001 0.00001 0.0001 0.001 0.01 0.1 ; do

    for res in 16 32 64 128; do 
        echo $res X $res
        python3 stone.py  $res  $res 0 $e > opla
        grep errv opla >> errors_$e
        grep divv opla >> divv_$e
        mv psurf.ascii psurf_${res}_${e}.ascii

    done 

done

